### ISSUE TITLE
FD800 Tiny

### ISSUE THREAD

**Issue by krocebow** [Hasi123/read-any-ppm#1]
Hi,

Thanks for sharing you core, I tried it and it kind of worked a little bit, I'm using a FD800 Tiny FrSky 8CH receiver, and I get the values but each 1-2secondes the values auto-center to 1500, example: if I pull down the throttle on my transmitter, the value is about 1000, and while I'm pulling down the value switches from 1000 to 1500 momentarely.

Is it because of the pulse width isn't the same? I found on the internet that frsky receivers have 300ms width.

**Comment by Hasi123** [comment]
There is no feature in the code, that would auto-center the values back to 1500. The initial values are 1500, but as soon as the first value gets read, it stays in the array until the next one overwrites it.
I have tested it with FrSky and had no issues. The code automatically adapts to the pulse width it gets.

Is it possible, that your receiver has a fault, or that it's failsafe is triggered somehow? Try to read it in betaflight, or whatever software you use on your flight controller.
